import "./globals.css";
import {Bree_Serif} from "next/font/google";

const mainFont = Bree_Serif({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={mainFont.className}
      >
        {children}
      </body>
    </html>
  );
}
